---
services:
- type: web
  name: mcp
  runtime: go
  buildCommand: go build -tags netgo -ldflags '-s -w' -o app
  startCommand: ./app --transport http
  envVars:
  - key: RENDER_API_KEY
    sync: false
  - key: REDIS_URL
    fromService:
      name: mcp-kv
      type: keyvalue
      property: connectionString
- type: keyvalue
  name: mcp-kv
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
